# Путь к файлу types.xml, сюда же будут сохраняться backup, сохраняя исходные значения
path: "C:\\путь_к_серверу\\mpmissions\\название_миссии\\db"

# Коэффициент лута (0.5 = в 2 раза меньше)
scale_factor: 0.5
